version: v0.14.0

selfservice:
  default_browser_return_url: http://localhost:3000/post-login
  flows:
    login:
      ui_url: http://localhost:4455/login
    registration:
      ui_url: http://localhost:4455/registration
    settings:
      ui_url: http://localhost:4455/settings
    recovery:
      ui_url: http://localhost:4455/recovery
    verification:
      ui_url: http://localhost:4455/verification
  methods:
    password:
      enabled: true
    webauthn:
      enabled: false

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
        - http://localhost:4455
  admin:
    base_url: http://kratos:4434/

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/schemas/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://user:pass@localhost:587/?skip_ssl_verify=true

log:
  level: debug

secrets:
  default:
    - please-change-me-random-secret

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 10

dsn: ${DSN}
